# ============================================================
# routers/symptom_vocab.py — Listahan ng KARANIWANG SINTOMAS (English + Tagalog)
#
# Ito ang "dictionary" na ginagamit ng Manage Diseases. Ang admin ay
# PUMIPILI lang mula rito (o mula sa HPO online); hindi na pwedeng mag-type
# ng kahit anong salita. Kaya hindi na makakapasok ang random na entry.
#
# Format:  ("Pangalan sa English", ["tagalog / ibang tawag", ...])
# Para magdagdag ng sintomas na wala pa rito: dagdagan lang ang listahan
# at i-restart ang server. Ang mga synonym ay awtomatikong magagamit
# sa paghahanap ng doktor (hal. i-type ang "lagnat" para lumabas ang Fever).
# ============================================================

SYMPTOM_VOCAB = [
    ("Fever", ["lagnat", "mainit ang katawan", "pyrexia"]),
    ("Chills", ["ginaw", "panginginig", "giniginaw"]),
    ("Cough", ["ubo"]),
    ("Phlegm", ["plema", "sputum", "mucus"]),
    ("Coughing up blood", ["pag-ubo ng dugo", "hemoptysis"]),
    ("Runny nose", ["sipon", "tumutulong sipon"]),
    ("Nasal congestion", ["baradong ilong", "barado ang ilong"]),
    ("Sneezing", ["pagbahin"]),
    ("Sore throat", ["masakit ang lalamunan", "sakit ng lalamunan"]),
    ("Hoarseness", ["pamamalat"]),
    ("Difficulty swallowing", ["hirap lumunok", "dysphagia"]),
    ("Shortness of breath", ["hirap huminga", "kakapusan ng hininga", "dyspnea", "difficulty breathing"]),
    ("Wheezing", ["humuhuni ang dibdib", "wheeze"]),
    ("Chest pain", ["sakit ng dibdib"]),
    ("Palpitations", ["pagtibok ng puso nang mabilis", "kabog ng dibdib"]),
    ("Rapid heartbeat", ["mabilis na tibok ng puso", "tachycardia"]),
    ("Headache", ["sakit ng ulo", "pananakit ng ulo"]),
    ("Dizziness", ["pagkahilo", "hilo", "vertigo"]),
    ("Fainting", ["pagkahimatay", "syncope"]),
    ("Confusion", ["pagkalito"]),
    ("Seizure", ["kombulsyon", "convulsion", "pangingisay"]),
    ("Neck stiffness", ["paninigas ng leeg"]),
    ("Numbness", ["pamamanhid", "tingling"]),
    ("Tremor", ["panginginig ng kamay", "nanginginig"]),
    ("Insomnia", ["hindi makatulog", "hirap matulog"]),
    ("Anxiety", ["pagkabalisa", "kaba"]),
    ("Irritability", ["iritable", "madaling mairita"]),
    ("Fatigue", ["pagod", "panghihina ng katawan", "tiredness"]),
    ("Weakness", ["panghihina", "body weakness"]),
    ("Muscle weakness", ["panghihina ng kalamnan"]),
    ("Muscle pain", ["sakit ng katawan", "myalgia", "pananakit ng kalamnan"]),
    ("Muscle cramps", ["pulikat"]),
    ("Joint pain", ["sakit ng kasukasuan", "arthralgia"]),
    ("Back pain", ["sakit ng likod"]),
    ("Leg pain", ["sakit ng binti"]),
    ("Pain", ["sakit"]),
    ("Swelling", ["pamamaga"]),
    ("Leg swelling", ["pamamaga ng binti", "edema"]),
    ("Swollen lymph nodes", ["pamamaga ng kulani", "lymph node swelling", "namamagang kulani"]),
    ("Abdominal pain", ["sakit ng tiyan", "pananakit ng tiyan"]),
    ("Abdominal bloating", ["pamamaga ng tiyan", "kabag", "bloating"]),
    ("Nausea", ["pagduduwal", "naduduwal"]),
    ("Vomiting", ["pagsusuka", "suka"]),
    ("Diarrhea", ["pagtatae", "lbm", "loose bowel movement"]),
    ("Constipation", ["pagtitibi", "hirap dumumi"]),
    ("Bloody stool", ["dugo sa dumi", "hematochezia"]),
    ("Pale stool", ["maputlang dumi"]),
    ("Heartburn", ["pangangasim ng sikmura", "acid reflux"]),
    ("Loss of appetite", ["kawalan ng gana kumain", "walang ganang kumain", "anorexia"]),
    ("Weight loss", ["pagbaba ng timbang", "pagpayat"]),
    ("Dehydration", ["pagkatuyot", "dehydrated"]),
    ("Poor feeding", ["hirap sumuso", "ayaw dumede"]),
    ("Excessive thirst", ["labis na pagkauhaw", "polydipsia", "sobrang uhaw"]),
    ("Frequent urination", ["madalas na pag-ihi", "polyuria"]),
    ("Painful urination", ["hapdi sa pag-ihi", "dysuria", "masakit umihi"]),
    ("Blood in urine", ["dugo sa ihi", "hematuria"]),
    ("Dark urine", ["maitim na ihi"]),
    ("Painful menstruation", ["masakit na regla", "dysmenorrhea"]),
    ("Missed period", ["hindi nagkaroon ng regla", "delayed menstruation"]),
    ("Vaginal discharge", ["lumalabas sa ari ng babae"]),
    ("Rash", ["pantal", "pamamantal", "skin rash"]),
    ("Itching", ["pangangati", "makati", "pruritus"]),
    ("Hives", ["pantal na makati", "urticaria"]),
    ("Blisters", ["paltos"]),
    ("Skin peeling", ["pagbabalat ng balat"]),
    ("Dry skin", ["tuyong balat"]),
    ("Flushed skin", ["pamumula ng balat"]),
    ("Excessive sweating", ["labis na pagpapawis", "hyperhidrosis"]),
    ("Night sweats", ["pagpapawis sa gabi"]),
    ("Hair loss", ["pagkalagas ng buhok"]),
    ("Jaundice", ["paninilaw", "dilaw na mata", "yellow skin"]),
    ("Bleeding", ["pagdurugo"]),
    ("Nosebleed", ["pagdurugo ng ilong", "epistaxis", "dumudugo ang ilong"]),
    ("Gum bleeding", ["pagdurugo ng gilagid"]),
    ("Easy bruising", ["pasa", "madaling magkapasa"]),
    ("Eye pain", ["sakit sa likod ng mata", "sakit ng mata"]),
    ("Red eyes", ["pamumula ng mata", "namumulang mata", "conjunctivitis"]),
    ("Eye discharge", ["muta"]),
    ("Blurred vision", ["panlalabo ng mata", "malabong paningin"]),
    ("Ear pain", ["sakit ng tainga", "earache"]),
    ("Toothache", ["sakit ng ngipin"]),
    ("Mouth sores", ["sugat sa bibig", "singaw", "mouth ulcers"]),
    ("Loss of smell", ["pagkawala ng pang-amoy", "anosmia"]),
    ("Loss of taste", ["pagkawala ng panlasa", "ageusia"]),
]
